# Config file for automatic testing at travis-ci.org

language: c

env:
  - LUA="Lua 5.1"
  - LUA="Lua 5.2"
  - LUA="Lua 5.3"
  - LUA="LuaJIT 2.0"

before_install:
  - bash .travis_setup.sh

install:
  - sudo apt-get update -qq
  - sudo luarocks install luasec
  - sudo luarocks install md5 1.2-1
  - sudo luarocks install luafilesystem
  - sudo luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - sudo luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - git clone git://github.com/Olivine-Labs/busted.git
  - cd busted
  - sudo luarocks make busted-scm-0.rockspec
  - cd ../


script: "busted spec"

notifications:
  recipients:
    - areski@gmail.com
  email:
    on_success: always
    on_failure: always